alter table reply AUTO_INCREMENT=1;

-- SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for reply
-- ----------------------------
-- DROP TABLE IF EXISTS `reply`;
-- CREATE TABLE `reply` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `code` varchar(11) DEFAULT NULL,
--   `codeid` varchar(11) DEFAULT NULL,
--   `imgurl` varchar(255) DEFAULT NULL,
--   `openid` varchar(255) DEFAULT NULL,
--   `content` varchar(600) DEFAULT NULL,
--   `date` varchar(255) DEFAULT NULL,
--   `author` varchar(255) DEFAULT NULL,
--   `nickName` varchar(255) DEFAULT NULL,
--   `avatarUrl` varchar(255) DEFAULT NULL,
--   `factor1` varchar(255) DEFAULT NULL,
--   `factor2` varchar(255) DEFAULT NULL,
--   `factor3` varchar(255) DEFAULT NULL,
--   `factor4` varchar(255) DEFAULT NULL,
--   `factor5` varchar(255) DEFAULT NULL,
--   `factor6` varchar(255) DEFAULT NULL,
--   `factor7` varchar(255) DEFAULT NULL,
--   `factor8` varchar(255) DEFAULT NULL,
--   `factor9` varchar(255) DEFAULT NULL,
--   `factor10` varchar(255) DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;